name: Recipely
options:
  minimumXcodeGenVersion: 2.3.0
  deploymentTarget:
    iOS: 16.0
  groupSortPosition: bottom
  createIntermediateGroups: true
  bundleIdPrefix: "com.tixomark"
  postGenCommand: pod update

packages:
  AdvancedNSAttributedStringPKJ:
    url: https://github.com/tixomark/AdvancedNSAttributedStringPKJ.git
    from: 1.0.0
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    from: 2.8.0
    
  
targets:
  Recipely:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Recipely
      - project.yml
      - swiftgen.yml
      - .swiftlint.yml
      - .swiftformat
      - Podfile
    dependencies:
      - package: AdvancedNSAttributedStringPKJ
      - package: Swinject
    scheme:
      testTargets:
        - RecipelyTests
    settings:
      base:
        SWIFT_VERSION: 5.0
        CURRENT_PROJECT_VERSION: 1.0.0
        MARKETING_VERSION: 1
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        ENABLE_USER_SCRIPT_SANDBOXING: false
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: true

        #ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
        #ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then

                "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
        
  RecipelyMock:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Recipely
      - project.yml
      - swiftgen.yml
      - .swiftlint.yml
      - .swiftformat
      - Podfile
    dependencies:
      - package: AdvancedNSAttributedStringPKJ
      - package: Swinject
    settings:
      base:
        SWIFT_VERSION: 5.0
        CURRENT_PROJECT_VERSION: 1.0.0
        MARKETING_VERSION: 1
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        ENABLE_USER_SCRIPT_SANDBOXING: false
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: true
        OTHER_SWIFT_FLAGS: "$(inherited) -D Free"
        
        #ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
        #ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then

                "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
        
  RecipelyTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - RecipelyTests
    dependencies:
      - target: Recipely
    settings:
      base:
        SWIFT_VERSION: 5.0
        CURRENT_PROJECT_VERSION: 1.0.0
        MARKETING_VERSION: 1
#        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        ENABLE_USER_SCRIPT_SANDBOXING: false
#        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: true
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
